---
title: "Assignment 2"
author: "XUAN ZHU"
date: "September 23, 2018"
output: pdf_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Rewrite the Lake Huron shiny application


```{r eruptions, echo=FALSE}
inputPanel(
  
  
  checkboxInput("smooth", label = "Add smoother?", value = FALSE)
)

renderPlot({
  
  if(input$smooth){
    scatter.smooth(LakeHuron, col="blue")
     lines(LakeHuron, col="red")
    }else{
  plot(LakeHuron)}; 
})

```

```{r}
library(ggplot2)
plot(LakeHuron)
# Deal with the data's format
Time<-c(1875:1972)
# Plot with scatters
ggplot(data = as.data.frame(LakeHuron),mapping = aes(x=Time,y=LakeHuron))+geom_point()
# Plot with lines
ggplot(data = as.data.frame(LakeHuron),mapping = aes(x=Time,y=LakeHuron))+geom_point()+geom_line(color="red")
# Plot with smoother
ggplot(data = as.data.frame(LakeHuron),mapping = aes(x=Time,y=LakeHuron))+geom_point()+geom_line(color="gray")+geom_smooth(stat = "smooth",color="red",se=F)
```


